# Default values for Codehorn Execution Services.

global:
  environment: production
  cloudsqlUrl: "jdbc:mysql://cloudsql-proxy-service.sql-proxy.svc.cluster.local:3306"
# Common configurations
common:
  restartPolicy: Always
# C++ Execution Service
cpp:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-cpp-execution-service
    pullPolicy: IfNotPresent
    sha: "sha256:7e661ae97a191c5ef4deae6ec5c37810ecaa30afb036db8cf9b71d46470d9e2b"
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "gcc:13"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Java Execution Service
java:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-java-execution-service
    pullPolicy: IfNotPresent
    sha: "sha256:c5747d4e1525f432c58c7718e14bfba7bd551dba031d75d7805ac9a0c3d35889"
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "openjdk:17-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Python Execution Service
python:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-python-execution-service
    pullPolicy: IfNotPresent
    sha: "sha256:6493ccee107d6cff2465c62c48390bd3d6113f6e867b5f651bc25ec6056e8bfa"
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "python:3.11-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Javascript Execution Service
javascript:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-javascript-execution-service
    pullPolicy: IfNotPresent
    sha: "sha256:223b7ad8557c2a92b91af52cae4cee564b2b72cd906efc55f735edceb7dfc982"
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "node:20-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Problems Service
problems:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-problems-service
    pullPolicy: IfNotPresent
    sha: "sha256:eebc2c69310504428c0fe0f3d36a6f02c932ba6030e615f43a64fba77accdff4"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Contest Service
contest:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-contest-service
    pullPolicy: IfNotPresent
    sha: "sha256:468740f96d627baa50448579446f77fcd4dafb77d16c98ab3bfd3a3135e9f270"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Daily Challenge Service
dailyChallenge:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-daily-challenge-service
    pullPolicy: IfNotPresent
    sha: "sha256:56c27a6c51890d515488b1be9083c9a3ee7624b0db89ef5b45b6b981660bb0f0"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# CodeSubmission Service
codeSubmission:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-code-submission-service
    pullPolicy: IfNotPresent
    sha: "sha256:dfe699067dac3a7cee068b29bb0f1aa62206b165accc01951a7568cce461e6b0"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# CodeExecution Service
codeExecution:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-code-execution-service
    pullPolicy: IfNotPresent
    sha: "sha256:8aa11abe519b017f5eb72ebdae5e2af1acfa743a30df3cf12ab52003e73987fa"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Gateway Service
gateway:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-gateway-service
    pullPolicy: IfNotPresent
    sha: "sha256:c5835d92a3560ac9d83cbc80bcf8159cb83417e1e5ccb1c4297d164b6b4c77ee"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# Auth Service
auth:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-auth-service
    pullPolicy: IfNotPresent
    sha: "sha256:a0fabf5540969eb744131030f95e50921eaa2542f280f04c1d562ccd430bb074"
  service:
    type: ClusterIP
    port: 80
  resources: {}
# ProblemSubmission Service
problemSubmission:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-problem-submission-service
    pullPolicy: IfNotPresent
    sha: "sha256:c5e670c85f556bf34b8e49190cb358b19fce448bd63bb7c228941ae48c1bd6fd"
  service:
    type: ClusterIP
    port: 8080
  resources: {}
# Consul Service
consul:
  enabled: true
  replicaCount: 1
  image:
    repository: hashicorp/consul
    pullPolicy: IfNotPresent
    tag: "2.0"
  service:
    type: ClusterIP
    port: 8500
  resources: {}
# Nginx LoadBalancer Service
nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources: {}
