# Default values for Codehorn Execution Services.

global:
  environment: production
  cloudsqlUrl: "jdbc:mysql://cloudsql-proxy-service.sql-proxy.svc.cluster.local:3306"

# Common configurations
common:
  restartPolicy: Always

# C++ Execution Service
cpp:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-cpp-execution-service
    pullPolicy: IfNotPresent
    sha: ""
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "gcc:13"
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Java Execution Service
java:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-java-execution-service
    pullPolicy: IfNotPresent
    sha: ""
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "openjdk:17-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Python Execution Service
python:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-python-execution-service
    pullPolicy: IfNotPresent
    sha: ""
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "python:3.11-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Javascript Execution Service
javascript:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-javascript-execution-service
    pullPolicy: IfNotPresent
    sha: ""
  sidecar:
    image:
      repository: docker
      tag: "24.0.7-dind"
      pullPolicy: IfNotPresent
    runnerImage: "node:20-slim"
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Problems Service
problems:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-problems-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Contest Service
contest:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-contest-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Daily Challenge Service
dailyChallenge:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-daily-challenge-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# CodeSubmission Service
codeSubmission:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-code-submission-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# CodeExecution Service
codeExecution:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-code-execution-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Gateway Service
gateway:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-gateway-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# Auth Service
auth:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-auth-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}

# ProblemSubmission Service
problemSubmission:
  enabled: false
  replicaCount: 1
  image:
    repository: irsathkareem/codehorn-problem-submission-service
    pullPolicy: IfNotPresent
    sha: ""
  service:
    type: ClusterIP
    port: 8080
  resources: {}

# Consul Service
consul:
  enabled: true
  replicaCount: 1
  image:
    repository: hashicorp/consul
    pullPolicy: IfNotPresent
    tag: "2.0"
  service:
    type: ClusterIP
    port: 8500
  resources: {}

# Nginx LoadBalancer Service
nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources: {}