spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: code-submission
          uri: lb://code-submission-service
          predicates:
            - Path=/code-submission/**
          filters:
            - StripPrefix=1

        - id: code-execution
          uri: lb://code-execution-service
          predicates:
            - Path=/code-execution/**
          filters:
            - StripPrefix=1

        - id: contest
          uri: lb://contest-service
          predicates:
            - Path=/contest/**
          filters:
            - StripPrefix=1

        - id: problems
          uri: lb://problems-service
          predicates:
            - Path=/problems/**
          filters:
            - StripPrefix=1

        - id: problem-submission
          uri: lb://problem-submission-service
          predicates:
            - Path=/problem-submission/**
          filters:
            - StripPrefix=1

        - id: daily-challenge
          uri: lb://daily-challenge-service
          predicates:
            - Path=/daily-challenge/**
          filters:
            - StripPrefix=1

        - id: cpp-execution
          uri: lb://cpp-execution-service
          predicates:
            - Path=/cpp-execution/**
          filters:
            - StripPrefix=1

        - id: java-execution
          uri: lb://java-execution-service
          predicates:
            - Path=/java-execution/**
          filters:
            - StripPrefix=1

        - id: python-execution
          uri: lb://python-execution-service
          predicates:
            - Path=/python-execution/**
          filters:
            - StripPrefix=1

        - id: javascript-execution
          uri: lb://javascript-execution-service
          predicates:
            - Path=/javascript-execution/**
          filters:
            - StripPrefix=1